[package]
name = "redis-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
cityhasher = "0.1.0"
rand = "0.9.0"
ansi_term = "0.12.1"
lzf = "1.0.0"
bytes = "1.10.1"
atoi = "2.0.0"
tokio = {version = "1.45.1", features = ["full"]}
tracing = "0.1.41"
